#ifndef PAL_CONFIG_H_INCLUDED
#define PAL_CONFIG_H_INCLUDED

#define HAS_POSIX_SEMAPHORES 1
#define HAVE_SEMAPHORE_H 1

#define HAVE_UCONTEXT_T 1
//#define HAVE_PT_REGS 1

// not there on android
//#define HAVE_GREGSET_T 1

#define HAVE_WORKING_CLOCK_GETTIME 1
#define ERROR_FUNC_FOR_GLOB_HAS_FIXED_PARAMS 1
#define HAVE_CLOCK_MONOTONIC 1

#define SYNCHMGR_SUSPENSION_SAFE_CONDITION_SIGNALING 1
#define HAVE_POLL 1
#define HAVE_PIPE2 1
#define HAVE_SYSCTL 1
#define HAVE_SYSCONF 1

#define HAVE_SCHED_GETCPU 1
#define HAVE_SCHED_GET_PRIORITY 1
#define HAVE_PTHREAD_GETCPUCLOCKID 1
#define HAVE_PTHREAD_GETATTR_NP 1
#define HAVE__SC_PHYS_PAGES 1

#endif